# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e000f30931ca8939acd445196b3fec9b857bf618b620d1df4fb54130715d7824e36844e0c2f36aceb4f7ed51b32c473bdb01f10215864a51b83cba22b8487c94

test:
  secret_key_base: ff2d6342a1b7e9728e55407e2d4fbe8199395090d9e371d53ef9534732bc0cd30827e699ca7d8333cfde213c5754658af4a27ff36c612190b3b84d1e34b31fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
